import { type Address } from 'viem'

// Contract addresses - Replace these with your deployed contract addresses
export const MOCK_ERC20_ADDRESS: Address = '0x5FbDB2315678afecb367f032d93F642f64180aa3'
export const P2P_LENDING_ADDRESS: Address = '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9'

// ERC20 ABI (Standard + Approve)
export const ERC20_ABI = [
  {
    name: 'name',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'string' }],
  },
  {
    name: 'symbol',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'string' }],
  },
  {
    name: 'decimals',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint8' }],
  },
  {
    name: 'balanceOf',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'allowance',
    type: 'function',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'approve',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    name: 'transfer',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ type: 'bool' }],
  },
] as const

// P2P Lending Contract ABI
export const P2P_LENDING_ABI = [
  // Lender functions
  {
    name: 'placeLenderOrder',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'amount', type: 'uint256' },
      { name: 'minRateBps', type: 'uint256' },
      { name: 'minSharesOut', type: 'uint256' },
      { name: 'deadline', type: 'uint256' },
    ],
    outputs: [],
  },
  // Borrower functions
  {
    name: 'placeBorrowOrder',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'amount', type: 'uint256' },
      { name: 'maxRateBps', type: 'uint256' },
      { name: 'minAmountOut', type: 'uint256' },
      { name: 'deadline', type: 'uint256' },
    ],
    outputs: [],
  },
  // Matching function
  {
    name: 'matchOrders',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'maxItems', type: 'uint256' }],
    outputs: [],
  },
  // Repayment function
  {
    name: 'repay',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'loanId', type: 'uint256' }],
    outputs: [],
  },
  // Withdraw function
  {
    name: 'withdraw',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },

  // Public storage getters (auto-generated by Solidity)
  {
    name: 'lenderOrders',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'orderId', type: 'uint256' }],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'owner', type: 'address' },
          { name: 'amount', type: 'uint128' },
          { name: 'minRateBps', type: 'uint32' },
          { name: 'createdAt', type: 'uint32' },
          { name: 'remaining', type: 'uint128' },
        ],
      },
    ],
  },
  {
    name: 'borrowOrders',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'orderId', type: 'uint256' }],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'owner', type: 'address' },
          { name: 'amount', type: 'uint128' },
          { name: 'maxRateBps', type: 'uint32' },
          { name: 'createdAt', type: 'uint32' },
          { name: 'remaining', type: 'uint128' },
        ],
      },
    ],
  },
  {
    name: 'loanPositions',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'loanId', type: 'uint256' }],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'lender', type: 'address' },
          { name: 'borrower', type: 'address' },
          { name: 'principal', type: 'uint128' },
          { name: 'rateBps', type: 'uint32' },
          { name: 'startTime', type: 'uint32' },
        ],
      },
    ],
  },

  // Next IDs (auto-generated by Solidity public uint256 vars)
  {
    name: 'nextLenderOrderId',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'nextBorrowOrderId',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    name: 'nextLoanId',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },

  // Helpers
  {
    name: 'previewInterest',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'loanId', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
  },

  // Events (optional for UI; kept minimal)
  {
    name: 'LenderOrderPlaced',
    type: 'event',
    inputs: [
      { name: 'orderId', type: 'uint256', indexed: true },
      { name: 'owner', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'minRateBps', type: 'uint256', indexed: false },
    ],
  },
  {
    name: 'BorrowOrderPlaced',
    type: 'event',
    inputs: [
      { name: 'orderId', type: 'uint256', indexed: true },
      { name: 'owner', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'maxRateBps', type: 'uint256', indexed: false },
    ],
  },
  {
    name: 'Matched',
    type: 'event',
    inputs: [
      { name: 'lenderOrderId', type: 'uint256', indexed: true },
      { name: 'borrowOrderId', type: 'uint256', indexed: true },
      { name: 'rateBps', type: 'uint256', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'loanId', type: 'uint256', indexed: false },
    ],
  },
  {
    name: 'LoanRepaid',
    type: 'event',
    inputs: [
      { name: 'loanId', type: 'uint256', indexed: true },
      { name: 'totalPaid', type: 'uint256', indexed: false },
      { name: 'interestPaid', type: 'uint256', indexed: false },
    ],
  },
] as const
